#!/bin/bash


DATE=$(date +"%m_%d_%Y-%H:%M")
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

FILENAME="$DIR/sunrise_$DATE.txt"

touch $FILENAME

echo "Executed on $DATE. Go @!" > $FILENAME

/usr/local/bin/pm2 stop hue-facade-test
